
FROM python:3.14


WORKDIR /app


RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*


COPY requirements.txt

RUN python -m venv venv

RUN venv/bin/pip install --no-cache-dir --upgrade pip && \
    venv/bin/pip install --no-cache-dir -r requirements.txt


COPY bot.py


RUN useradd -m -u 1000 botuser && \
    chown -R botuser:botuser /app
USER botuser


CMD ["venv/bin/python", "bot.py"]
